### ISSUE TITLE
symbol definition is void perject-mode

### ISSUE THREAD

**Issue by wereket** [overideal/perject#2]
my config 
https://github.com/wereket/dotfiles/blob/main/dot_emacs.d/config.org#perject-an-emacs-package-for-working-with-projects

**Comment by overideal** [comment]
It is hard to tell for me without further information, but I think the reason it is not working is because the :after savehist line defers the loading of the perject block.
You can try removing this line or modifying the savehist block (also see the example configuration of perject) in your configuration (which I suspect is not being loaded, so perject is not loaded either).

**Comment by overideal** [comment]
I think it is fair to close this, since it seems to be a configuration issue.
But feel free to reopen if you require further help.
