### ISSUE TITLE
Perject frame-title incompatible with other package constructs.

### ISSUE THREAD

**Issue by mcmillanbb** [overideal/perject#5]
First of all, thank you for the excellent package! I've been using emacs for a couple years, and had never gotten the standard project tools to work how I wanted, until I found this one.

Now, my issue: the way that perject handles the frame title is not compatible with other packages using the frame title. That is to say, in perject frames, setting the variable frame-title-format has no effect. This causes conflict, for example, with org-mode. With org-timer-display set to 'frame-title, a call to org-mode-set-timer should display the timer to the right of the "collection|project" in the title. Org handles this by adding an element to the list frame-title-format, similar to how mode-line-format is handled.

I hope that the fix would be as simple as changing perject to update the title using frame-title-format. Unless there is some deeper reason that perject does otherwise. But if it's that simple, I am happy to submit a pull request.

**Comment by overideal** [comment]
Thank you, that is very nice to hear!

Let me first comment on the particular org issue: Testing this in emacs -Q (no configuration, in particular no packages enabled), setting `org-timer-display` to `'frame-title` does not actually ever show the timer in the frame title. Looking through the org code, I understand why this is case and wonder if that is intentional or not. Does it show it for you?

Regarding the general "incompatibility" of the frame-title in perject.
There are two ways to set the frame title: Either via `frame-title-format` (which serves as a default) or via the `set-frame-parameter` (this overwrites the other way and only applies to a particular frame). I chose the second version, which is why in general changes to the first version are not detected. I think my reasoning was that everything in perject is "frame-local" (i.e. switching frame changes the context). In particular, if a frame does not belong to a project, it is not influenced by this method. Do you think that it is better to use the first version?
As an aside: One can always set `perject-frame-title-format` to `nil` and change the frame titles manually in the emacs config file.

**Comment by mcmillanbb** [comment]
Re: org-timer, I do see the behavior you mention, which I guess is a minor bug. My understanding is that the default frame-title-format changed from a list to a string at some point, and the timer code only handles it as a list, by appending the timer. So it is easy to fix, by making frame-title-format a list. For example, in my init, I set perject-frame-title-format to nil (as you helpfully suggest) and, to keep the perject information:
(setq frame-title-format '((:eval (when (perject-current)
                                    (concat "< " (car (perject-current)) " | " (cdr (perject-current)) " >")))))

In fact, I agree with your reasoning, the frame-locality of projects is a large part of why I prefer perject over the other project tools. Ideally, you could name the frame and then include the name as part of the frame-title-format construct. But it doesn't seem emacs is set up so that you can do that. (And it is an issue not just for this package, I run into the same problem with the noter package---it changes the frame name and thus no timer shows while I read pdfs.)

As for what to do, I prefer to keep the frame-title-format, but did miss the perject information. That is why I added the perject cookie as above. Perhaps this would be a reasonable compromise, to create a cookie and then add it automatically to frame-title-format. Compare how org handles timers, adding and removing them as needed.

**Comment by overideal** [comment]
Interesting.
Let me first comment on the org-timer issue. Yes, it is easy to fix for the default value of `frame-title-format`. But (if I understand it correctly) such a fix will generally not work once the user has sufficiently changed `frame-title-format` (since one would have to essentially parse an arbitrary value in the same format as `mode-line-format`).
But org-timer should probably at least work with the default value, so if you are interested, you could report this bug to the Org mailing list (I don't know if the bug is already known).

Because of the above, I think "adding to the already existing value" will not work well in the general case. It is interesting how `org-clock` handles this. They make a backup of `frame-title-format` and simply temporarily overwrite its value while the user is clocked in (thus during this time, only the "clock information" is shown). One could adapt this approach to perject, but it would essentially behave the same as the current solution and in particular would not solve the problem you have with org-timer. Any thoughts?

Ultimately, it seems hard to reasonably combine two "mode line information" into a single one and probably the only solution is a custom function written by the user.

**Comment by mcmillanbb** [comment]
Hmm, in my version of org (9.7.16), org-timer-set-timer and org-timer-stop both call the function org-timer-set-mode-line. If the timer is starting, this appends '(org-timer-mode-line-string) to the frame-title-format. If the timer is stopping, it delq's org-timer-mode-line-string from the list. As long as frame-title-format is a list, this doesn't break any other elements.
(I think the append is where the bug is, append doesn't work if frame-title-format is not a list. And I agree, it's on my list to report on the Org mailing list.)

While perject could do something similar to this, I think the easier approach is just to provide a perject-frame-title-cookie that the user can plonk into their frame title. The cookie would be a function that returns the empty string on non-perject frames and "collection | project" on perject frames. In fact, you've almost already provided this, the function perject-frame-title would work if it was able to grab its values from the current frame.
This is essentially what I have done, viz:

```
(setq frame-title-format '((:eval (perject-title-cookie))))

(require 'perject)
(defun perject-title-cookie ()
  (when (perject-current)
    (concat "< " (car (perject-current)) " | " (cdr (perject-current)) " >")))
```

This works fine for my purposes, and works with org-timer. This way it is easy to add any other mode-line information to the frame-title, just appending it to the list.
The trickiest part might be in communicating to users how to use it, unless perject automatically adds its cookie to title.

By the way, the solution here works for me, and I don't know how many people worry about the title bar, so it is totally fair if you decide the simplest solution is to leave matters as is.

**Comment by overideal** [comment]
As you mentioned, this is not really relevant for perject, but let me just comment on this for completeness:
- You might have misread, I was talking about `org-clock` instead of `org-timer` in the second paragraph of my previous comment.
- The point that I was trying to make is that simply appending to the list will not work in general, even if `frame-title-format` is a list. For example, suppose that `frame-title-format` is set to
```
(multiple-frames "%b"
		 ("" "%b - GNU Emacs at " system-name))
```
(the default value). This is a list, but simply appending to it
```
(setq frame-title-format
	      (append frame-title-format '(org-timer-mode-line-string)))
```
like is done in `org-timer-set-mode-line` will not work, because of the way `frame-title-format` is interpreted (see the documentation of `mode-line-format`). To make it work for all possible values of `frame-title-format` (which could in theory have lists of lists of lists) one would need to parse it, which seems like overkill. This is maybe why in `org-clock` they use the implementation I mentioned above.

It seems to me like there is no "best practice" for modifying the frame title from within a package, so I will keep the implementation as it is for now. Though I do like the "cookie" idea.

Thank you for the interesting discussion.

**Comment by mcmillanbb** [comment]
Ah, you are correct, I misread! Thanks for clarifying your point to me.

As well, thanks for discussing the issue.
